### ISSUE TITLE
problem with my github web site

### ISSUE THREAD

**Issue by Gwinant** [Gwinant/Gwinant.github.io#1]
Hello,
I've got some problems to make my github`s web site. I have already created my repository with the right name (user.name.github.io) with a README page and an html file but when I click on the link in order to see it, only my README page is seen/read and my html page is just ignored and I cannot understand why. Also, if I remove my README page, the link will guide us to a 404 error.
I would be gratful if you could explain me why !
Thank you so much for your attention and have a nice day,
Guillaume

**Comment by lucas-salves** [comment]
Hi, my apologies for the delay.
Take a look to this:
https://gist.github.com/TylerFisher/6127328
As you can see, the main file should be named index.html
>Move your website's files into the folder that GitHub just created when you made the repository. IMPORTANT: Your homepage HTML file must be called "index.html", and it must exist in the top-level directory.

If it still doesn't work, go get some coffee, it can take 5-10 minutes to the changes reflect.

**Comment by Gwinant** [comment]
Oh, thank you so much !

Indeed I've try what you said and indeed the problem was exactly what you meant.

Thanks for your quick answer and have nice day,

Guillaume
________________________________
De : Lucas Sousa Alves ***@***.***>
Envoyé : jeudi 9 décembre 2021 15:39
À : Gwinant/Gwinant.github.io ***@***.***>
Cc : Guillaume Winant ***@***.***>; State change ***@***.***>
Objet : Re: [Gwinant/Gwinant.github.io] problem with my github web site (Issue #1)


Hi, my apologies for the delay.
Take a look to this:
https://gist.github.com/TylerFisher/6127328<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgist.github.com%2FTylerFisher%2F6127328&data=04%7C01%7Cguillaume.winant%40student.uclouvain.be%7C27f86942b9064d78e21f08d9bb21b666%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637746575729628064%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=moOGBwK7l0%2BHOKd9an8HJlZUuR8XDl1VzeqLp5ebvOo%3D&reserved=0>
As you can see, the main file should be named index.html

Move your website's files into the folder that GitHub just created when you made the repository. IMPORTANT: Your homepage HTML file must be called "index.html", and it must exist in the top-level directory.

If it still doesn't work, go get some coffee, it can take 5-10 minutes to the changes reflect.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGwinant%2FGwinant.github.io%2Fissues%2F1%23issuecomment-989912977&data=04%7C01%7Cguillaume.winant%40student.uclouvain.be%7C27f86942b9064d78e21f08d9bb21b666%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637746575729628064%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mhYFdyAKU2e8f9CsFo%2FiNmSX%2BNo5W0Z2WvDtIK%2FO%2BnY%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWVFOTQ5252C2N2HZRJD5FTUQC5SFANCNFSM5JT2GVIQ&data=04%7C01%7Cguillaume.winant%40student.uclouvain.be%7C27f86942b9064d78e21f08d9bb21b666%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637746575729784279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1VzMqCUExLomrfiUVxm0cLGqqEskbazU%2FVyenfudeJs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cguillaume.winant%40student.uclouvain.be%7C27f86942b9064d78e21f08d9bb21b666%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637746575729784279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2FEde9WQ3mCZuyygfzuwBT2FtOundICcYfr4zvQze5XI%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cguillaume.winant%40student.uclouvain.be%7C27f86942b9064d78e21f08d9bb21b666%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637746575729784279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XXH7yCSpgsrLZvLmOiBbtSZKjNREYVcBIbmex5YCMWE%3D&reserved=0>.
